addons:
  apt:
    packages:
      - nodejs
language: python
python:
  - '3.8'
sudo: false
env:
  - TOXENV=eslint
  - TOXENV=csslint
  - TOXENV=quality
  - TOXENV=django22
  - TOXENV=django30
  - TOXENV=django31
before_install:
  - pip install -U pip
  - export BOTO_CONFIG=/dev/null
cache:
  directories:
    - $HOME/.cache/pip
install:
  - make requirements_travis
script:
  - tox
branches:
  only:
    - master
after_success: coveralls
